### ISSUE TITLE
json 数据回显

### ISSUE THREAD

**Issue by Buildvora** [LvHuaiSheng/gzm-design#11]
1、通过后端返回json数据 回显出对应画布内容

2、可以直接生成图片

**Comment by LvHuaiSheng** [comment]
> 1、通过后端返回json数据 回显出对应画布内容
> **在左上角“文件”中有个导入json的功能，可以把json值导入到当前页面，加载后端的数据可以参考这个来实现，可以配合切换页面来达到不同页面的内容导入；**
> 2、可以直接生成图片
>**关于生成图片，在右上角有个另存为按钮，可以下载出当前画布图片**

**Comment by provenceo** [comment]
需要搭配canvas.zoomToFit() 来实现吧

**Comment by Buildvora** [comment]
> > 1、通过后端返回json数据 回显出对应画布内容
> > **在左上角“文件”中有个导入json的功能，可以把json值导入到当前页面，加载后端的数据可以参考这个来实现，可以配合切换页面来达到不同页面的内容导入；**
> > 2、可以直接生成图片
> > **关于生成图片，在右上角有个另存为按钮，可以下载出当前画布图片**
需要搭配canvas.zoomToFit() 来实现吧
<img width="657" alt="image" src="https://github.com/LvHuaiSheng/gzm-design/assets/43238325/4add74b2-34b6-4b0b-9246-8dd6e91b79a8">
<img width="917" alt="image" src="https://github.com/LvHuaiSheng/gzm-design/assets/43238325/c991a89c-2502-48bd-917e-049bed7cee71">

**Comment by LvHuaiSheng** [comment]
canvas.zoomToFit()在importJsonToCurrentPage里有调用，会在json导入后执行，生效的前提是画布已经初始化完成以后
