### ISSUE TITLE
如何把svg导入到编辑器里面?

### ISSUE THREAD

**Issue by DullBird14** [LvHuaiSheng/gzm-design#12]
想把svg导入到编辑器中编辑。
需要把svg转换成json再导入么?
现在的json格式是按照什么逻辑定义的？有文档么

**Comment by LvHuaiSheng** [comment]
json就是leafer的格式
导入svg可以使用图片元素来加载svg，在官网上有对应的文档
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月07日 11:24 |
| 收件人 | LvHuaiSheng/gzm-design ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [LvHuaiSheng/gzm-design] 如何把svg导入到编辑器里面? (Issue #12) |

想把svg导入到编辑器中编辑。
需要把svg转换成json再导入么?
现在的json格式是按照什么逻辑定义的？有文档么
