### ISSUE TITLE
富文本编辑器 输入空格 会不显示文字

### ISSUE THREAD

**Issue by Buildvora** [LvHuaiSheng/gzm-design#13]
![image](https://github.com/LvHuaiSheng/gzm-design/assets/43238325/00dc7e68-58bf-4e48-a668-7bbfbe4972a3)
![image](https://github.com/LvHuaiSheng/gzm-design/assets/43238325/1eb56627-f448-43ad-92a6-cfa951595b15)
![image](https://github.com/LvHuaiSheng/gzm-design/assets/43238325/0ad6f604-474d-47dc-ae78-21fc358f2358)

**Comment by LvHuaiSheng** [comment]
已修复
