### ISSUE TITLE
Ts类型太多写错的了兄弟

### ISSUE THREAD

**Issue by Diven-xinhai** [LvHuaiSheng/gzm-design#14]
项目很好，但是代码问题有点多啊，整个项目ts类型几乎都有点问题
![image](https://github.com/LvHuaiSheng/gzm-design/assets/54425515/a8288ec6-e096-4102-a251-3dcbe7e2b73b)

**Comment by LvHuaiSheng** [comment]
感谢指出，因为是个业余的前端 ts用起来还不太上手，后面会开启强校验调整下

**Comment by ilaziness** [comment]
@LvHuaiSheng 老哥这么牛逼，全都是前端项目，还搞个海报设计器，说你是业余前端。。。

**Comment by LvHuaiSheng** [comment]
@ilaziness 确实不专业纯业余，做前端算是兴趣 对一些设计器情有独钟😂😂相关的ts问题欢迎pr一起来修复
