### ISSUE TITLE
老哥这个项目能开源后端吗

### ISSUE THREAD

**Issue by miaomiaojianglove** [LvHuaiSheng/gzm-design#15]
老哥这个项目能开源后端吗

**Comment by LvHuaiSheng** [comment]
目前还没有后端，只是纯前端项目

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月25日 19:04 |
| 收件人 | LvHuaiSheng/gzm-design ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [LvHuaiSheng/gzm-design] 老哥这个项目能开源后端吗 (Issue #15) |

老哥这个项目能开源后端吗
