### ISSUE TITLE
预览地址中文本元素双击不显示

### ISSUE THREAD

**Issue by smile-stars** [LvHuaiSheng/gzm-design#17]
双击文本，文本消失
![image](https://github.com/user-attachments/assets/9091a1f0-e3ea-456f-9ec2-c4b7b7d2435d)

**Comment by LvHuaiSheng** [comment]
感谢反馈，双击编辑文本目前存在问题，编辑临时可以先用右侧的输入框来填写，等修复了我会来关闭这个issues

**Comment by LvHuaiSheng** [comment]
最新代码已正常
