### ISSUE TITLE
oos 域名不支持 https 导致模板资源加载失败的问题

### ISSUE THREAD

**Issue by renxia** [LvHuaiSheng/gzm-design#20]
![20240820095117](https://github.com/user-attachments/assets/12c9d021-5d0a-4e6b-82ec-b6ce4843e669)

尝试自部署了一下，由于基于 https 方式访问，发现模板中存在许多访问 oss.guozimi.cn 域名的图片资源，由于该域名不支持 https，会导致加载失败，如图所示。

是否可以将该域名配置一下 SSL 证书，支持一下 https 呢。
如果是证书方面存在问题，我这里有一篇基于 acme 免费生成与续期泛域名SSL证书的实践记录可参考一下：
https://lzw.me/a/acme-sh-dnspod-api-nginx.html

**Comment by LvHuaiSheng** [comment]
ssl证书目前是有的，但是启用https后oss那边会收取流量费，后面我看看换个oss来启用

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月20日 09:58 |
| 收件人 | LvHuaiSheng/gzm-design ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [LvHuaiSheng/gzm-design] oos 域名不支持 https 导致模板资源加载失败的问题 (Issue #20) |

20240820095117.png (view on web)

尝试自部署了一下，由于基于 https 方式访问，发现模板中存在许多访问 oss.guozimi.cn 域名的图片资源，由于该域名不支持 https，会导致加载失败，如图所示。

是否可以将该域名配置一下 SSL 证书，支持一下 https 呢。
如果是证书方面存在问题，我这里有一篇基于 acme 免费生成与续期泛域名SSL证书的实践记录可参考一下：
https://lzw.me/a/acme-sh-dnspod-api-nginx.html

**Comment by LvHuaiSheng** [comment]
oss地址可以使用https了
