### ISSUE TITLE
色板问题：纯色与线性/径向渐变切换时，取色指示点 不能紧跟鼠标

### ISSUE THREAD

**Issue by smile-stars** [LvHuaiSheng/gzm-design#22]
https://github.com/user-attachments/assets/5fa24613-90d7-4e32-9083-2a47af0a7cbb

**Comment by LvHuaiSheng** [comment]
问题已修复

**Comment by smile-stars** [comment]
> 问题已修复

好的大佬，但是貌似出现了一个新的问题
描述：径向渐变，添加节点，给每一个节点设置颜色时，第一次无法拖动下方的色条，选中颜色之后才可以拖动

https://github.com/user-attachments/assets/eaa08f4f-31ea-4cc1-b395-0c22ac0013a4
