### ISSUE TITLE
色板，颜色为#FFFFFF或者是#000000时，下方的色相条无法拖动

### ISSUE THREAD

**Issue by smile-stars** [LvHuaiSheng/gzm-design#23]
![650bc88cc66b329c496cd289c1d99b1](https://github.com/user-attachments/assets/47409b95-382d-4c1d-8bfd-c861339f61ac)

https://github.com/user-attachments/assets/8ed1f407-25a8-4d42-8a6e-16f22c704a45

**Comment by LvHuaiSheng** [comment]
收到反馈，我排查下问题


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月21日 09:06 |
| 收件人 | LvHuaiSheng/gzm-design ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [LvHuaiSheng/gzm-design] 色板，颜色为#FFFFFF或者是#000000时，下方的色相条无法拖动 (Issue #23) |

650bc88cc66b329c496cd289c1d99b1.png (view on web)

https://github.com/user-attachments/assets/8ed1f407-25a8-4d42-8a6e-16f22c704a45

**Comment by smile-stars** [comment]
> 收到反馈，我排查下问题
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年09月21日 09:06 | | 收件人 | LvHuaiSheng/gzm-design ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [LvHuaiSheng/gzm-design] 色板，颜色为#FFFFFF或者是#000000时，下方的色相条无法拖动 (Issue #23) | 650bc88cc66b329c496cd289c1d99b1.png (view on web) https://github.com/user-attachments/assets/8ed1f407-25a8-4d42-8a6e-16f22c704a45 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好的大佬。另外我今天发现，不只是#000与##fff有这个问题，黑、白、灰这种没有色相属性的颜色，底下色相条都是无法拖动的

**Comment by LvHuaiSheng** [comment]
此问题已修复
